spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_banking
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  application:
    name: banking-backend

jwt:
    secret: your-super-secret-key-your-super-secret-key
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

server:
  port: 8080